### ISSUE TITLE
question about question_generator.py 

### ISSUE THREAD

**Issue by kkwhale7** [Yuqifan1117/HalluciDoctor#11]
为什么喂给gpt的时候，不要求他提出关于数量的疑问呢？
{caption}\nPlease give me meaningful and answerable questions corresponding to the following answers based on the given context to help me understand the context. Please ensure that each question doesn't involve 'How many' and is concise to exactly match the corresponding answer. Your answer needs to be divided into points, separated by '\n' between each point, and the number of points should be the same as the number of 'Answer' points I provided. Please answer in plain text (without formatting such as markdown)\nAnswer: {answer}"}]
实际上训练VLM的时候，我这边的数据往往不存在对象和实体的幻觉，更多的是对于数量的幻觉。

**Comment by Yuqifan1117** [comment]
Understanding quantities and spatial relationships is a more complex capability for VLMs, and even expert models struggle to handle it effectively. Therefore, introducing quantity or spatial-related questions for cross-checking may lead to more hallucinations inversely. Nevertheless, this type of hallucination is indeed an important issue, and precise detection and elimination of such hallucinations are promising areas for future research.
