### ISSUE TITLE
关于_VOCAB_PATH 的问题

### ISSUE THREAD

**Issue by guyuisland** [Yuqifan1117/HalluciDoctor#12]
我运行consistency_crosscheck.py 时发现evaluation_utils 的_VOCAB_PATH为空，这个好像运行不了，应该怎么处理？

**Comment by Yuqifan1117** [comment]
You can refer to our INSTALL.md of BEM evaluation: https://huggingface.co/google/bert_uncased_L-12_H-768_A-12/blob/main/vocab.txt into **_VOCAB_PATH** in models/evaluation_utils.py;
