### ISSUE TITLE
Some question about img dataset?

### ISSUE THREAD

**Issue by shipengai** [Yuqifan1117/HalluciDoctor#3]
In [https://github.com/Yuqifan1117/HalluciDoctor/blob/main/INSTALL.md](url)  where is /home/qifan/datasets/coco/object_sample1 ?

**Comment by Yuqifan1117** [comment]
https://github.com/Yuqifan1117/HalluciDoctor/blob/2afdbd92073e2653a7eec32d86cb978025d1ecd6/models/seesaw_counterfactual_generation.py#L126C94-L126C94
It saves the images of coco_objects generated by Stable Diffusion v1.5, we use this to generate the target hallucinatory objects.

**Comment by shipengai** [comment]
@Yuqifan1117 Thanks for your reply.Can you share the images you generated ?

**Comment by shipengai** [comment]
与[refined_datasets/expanded_LLaVA++_dataset.json](url)对应的生成图片
