### ISSUE TITLE
运行好question_generator.py后是这样吗？

### ISSUE THREAD

**Issue by 599046587lz** [Yuqifan1117/HalluciDoctor#4]

**Comment by 599046587lz** [comment]
<img width="912" alt="111" src="https://github.com/Yuqifan1117/HalluciDoctor/assets/56827890/16227654-5c98-44bd-8274-510ea7524f63">
questions和answers都为空

**Comment by Yuqifan1117** [comment]
我认为这样的结果没有问题，question和answer是原本输出用于测试的，将answer即对应valid_answers，而将llm_questions进行split拆分后就是question的值。

**Comment by 599046587lz** [comment]
可是这样在blip2_candidate_answer_generator.py产生回答的时候，37行zip操作会有问题吧，输出会为空

**Comment by Yuqifan1117** [comment]
这是因为answer值没有填入造成的，我已经对question_generator.py进行了更新，加入了填充部分。

**Comment by 599046587lz** [comment]
请问minigpt4你是用的Vicuna吗？在minigpt4_candidate_answer_generator.py中是否需要对img_list进行chatmodel.encode_img(img_list)操作，不然会有下面的device报错，即便device默认让他在cuda上，也会有第二张图片的报错。
<img width="1079" alt="1111" src="https://github.com/Yuqifan1117/HalluciDoctor/assets/56827890/ef94a9e6-5a20-4255-8167-794d9ff5b539">
<img width="1080" alt="2222" src="https://github.com/Yuqifan1117/HalluciDoctor/assets/56827890/fdbf37d7-0e03-44bb-822d-d7e874e3e7a0">
