### ISSUE TITLE
MME result

### ISSUE THREAD

**Issue by LAW1223** [Yuqifan1117/HalluciDoctor#9]
Hello, this is very good work. But when I use the model on llava with llava+ data, I found that the model works poorly on MME. I checked the data, llava+ is describing the image of a single round of dialogue data, using only llava+, the model does not perform very well with INSTRUCTION FOLLOWING, it takes a long time to test on MME benchmark, and after testing it there are no results! I checked the output as follows. Can you disclose your model checkpoints and test logs?
![0ee7aa28f1b021db5c2aca76aca3513](https://github.com/Yuqifan1117/HalluciDoctor/assets/112919344/aa800e3b-8357-4de3-bc74-ed6340210d13)

**Comment by Yuqifan1117** [comment]
Thanks for your attention! Considering the poor instruction following the original vicuna v0, we have adopted vicuna v1.5 uniformly to make a fair comparison with LLaVA (only using LLaVA or LLaVA+ data instead of others). By forcing the output to include yes/no, we get the following MME test logs.

=========== Perception ===========
total score: 1110.7094385492892 

         existence  score: 185.0
         count  score: 88.33333333333334
         position  score: 63.333333333333336
         color  score: 80.0
         posters  score: 146.59863945578232
         celebrity  score: 103.82352941176471
         scene  score: 150.25
         landmark  score: 74.12060301507537
         artwork  score: 101.75
         OCR  score: 117.5


=========== Cognition ===========
total score: 308.92857142857144 

         commonsense_reasoning  score: 101.42857142857142
         numerical_calculation  score: 80.0
         text_translation  score: 70.0
         code_reasoning  score: 57.5

BTW, the Lora model of llava+ is provided [here](https://drive.google.com/drive/folders/11p0CCSZ-jNL-r5Sm5ixJ_Oz-sDll9o2l?usp=sharing), which can merged with vicuna 1.5

The original LLaVA results (with vicuna 1.5) are listed as follows,
=========== Perception ===========
total score: 979.507162161347 

         existence  score: 170.0
         count  score: 65.0
         position  score: 51.66666666666667
         color  score: 60.0
         posters  score: 107.82312925170069
         celebrity  score: 77.05882352941177
         scene  score: 155.5
         landmark  score: 141.70854271356785
         artwork  score: 78.25
         OCR  score: 72.5


=========== Cognition ===========
total score: 244.28571428571428 

         commonsense_reasoning  score: 79.28571428571429
         numerical_calculation  score: 52.5
         text_translation  score: 57.5
         code_reasoning  score: 55.0

**Comment by LAW1223** [comment]
Got it! Thank you for your prompt response!
________________________________
发件人: qf_yy1999 ***@***.***>
发送时间: 2024年5月8日 16:16
收件人: Yuqifan1117/HalluciDoctor ***@***.***>
抄送: Yexin LIU ***@***.***>; Author ***@***.***>
主题: Re: [Yuqifan1117/HalluciDoctor] MME result (Issue #9)


Thanks for your attention! Considering the poor instruction following the original vicuna v0, we have adopted vicuna v1.5 uniformly to make a fair comparison with LLaVA (only using LLaVA or LLaVA+ data instead of others). By forcing the output to include yes/no, we get the following MME test logs.

=========== Perception ===========
total score: 1110.7094385492892

     existence  score: 185.0
     count  score: 88.33333333333334
     position  score: 63.333333333333336
     color  score: 80.0
     posters  score: 146.59863945578232
     celebrity  score: 103.82352941176471
     scene  score: 150.25
     landmark  score: 74.12060301507537
     artwork  score: 101.75
     OCR  score: 117.5


=========== Cognition ===========
total score: 308.92857142857144

     commonsense_reasoning  score: 101.42857142857142
     numerical_calculation  score: 80.0
     text_translation  score: 70.0
     code_reasoning  score: 57.5


BTW, the Lora model of llava+ is provided here<https://drive.google.com/drive/folders/11p0CCSZ-jNL-r5Sm5ixJ_Oz-sDll9o2l?usp=sharing>, which can merged with vicuna 1.5

The original LLaVA results (with vicuna 1.5) are listed as follows,
=========== Perception ===========
total score: 979.507162161347

     existence  score: 170.0
     count  score: 65.0
     position  score: 51.66666666666667
     color  score: 60.0
     posters  score: 107.82312925170069
     celebrity  score: 77.05882352941177
     scene  score: 155.5
     landmark  score: 141.70854271356785
     artwork  score: 78.25
     OCR  score: 72.5


=========== Cognition ===========
total score: 244.28571428571428

     commonsense_reasoning  score: 79.28571428571429
     numerical_calculation  score: 52.5
     text_translation  score: 57.5
     code_reasoning  score: 55.0


―
